-- Database: Projeto Mercado

CREATE DATABASE "Projeto Mercado"
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'Portuguese_Brazil.1252'
    LC_CTYPE = 'Portuguese_Brazil.1252'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;

CREATE TABLE ESTADOS
(
	COD_ESTADO SERIAL CONSTRAINT PK_ESTADO PRIMARY KEY,
	NOME VARCHAR(30) CONSTRAINT NN_NOME_ESTADO NOT NULL,
	SIGLA CHAR(2) CONSTRAINT NN_SIGLA_ESTADO NOT NULL
);

CREATE TABLE CIDADE
(
	COD_CIDADE SERIAL CONSTRAINT PK_CIDADE PRIMARY KEY,
	NOME VARCHAR(30) CONSTRAINT NN_NOME_CIDADE NOT NULL,
	ESTADO INTEGER CONSTRAINT FK_ESTADO_CIDADE REFERENCES ESTADOS(COD_ESTADO)
);

CREATE TABLE TIPOS_PESSOA
(
	COD_TIPO_PESSOA SERIAL CONSTRAINT PK_TIPO_PESSOA PRIMARY KEY,
	TIPO_PESSOA VARCHAR(30) CONSTRAINT NN_TIPO_PESSOA NOT NULL
);

CREATE TABLE PESSOAS
(
	COD_PESSOA SERIAL CONSTRAINT PK_PESSOA PRIMARY KEY,
	NOME VARCHAR(30) CONSTRAINT NN_NOME_PESSOA NOT NULL,
	CPF_CNPJ VARCHAR(14) CONSTRAINT NN_CPF_CNPJ_PESSOA NOT NULL,
	RG VARCHAR(9),
	SALARIO MONEY,
	RUA VARCHAR(30) CONSTRAINT NN_RUA_PESSOA NOT NULL,
	NUMERO VARCHAR(5) CONSTRAINT NN_NUMERO_PESSOA NOT NULL,
	BAIRRO VARCHAR(30) CONSTRAINT NN_BAIRRO_PESSOA NOT NULL,
	CEP VARCHAR(8) CONSTRAINT NN_CEP_PESSOA NOT NULL,
	CIDADE INTEGER CONSTRAINT FK_CIDADE_PESSOA REFERENCES CIDADE(COD_CIDADE),
	TIPOS_PESSOA INTEGER CONSTRAINT FK_TIPOS_PESSOA_PESSOA REFERENCES TIPOS_PESSOA(COD_TIPO_PESSOA)
);

CREATE TABLE DESPESAS
(
	COD_DESPESA SERIAL CONSTRAINT PK_DESPESA PRIMARY KEY,
	VALOR MONEY CONSTRAINT NN_VALOR_DESPESAS NOT NULL,
	OBSERVACAO VARCHAR(100) CONSTRAINT NN_OBSERVACAO_DESPESAS NOT NULL,
	DATA_DESPESA TIMESTAMP CONSTRAINT NN_DATA_DESPESAS NOT NULL,
	VENCIMENTO TIMESTAMP CONSTRAINT NN_VENCIMENTO_DESPESAS NOT NULL,
	DATA_PAGAMENTO TIMESTAMP,
	MULTA MONEY,
	PESSOA INTEGER CONSTRAINT FK_PESSOA_DESPESAS REFERENCES PESSOAS(COD_PESSOA)
);

CREATE TABLE VENDAS
(
	COD_VENDAS SERIAL CONSTRAINT PK_VENDAS PRIMARY KEY,
	OBSERVACAO VARCHAR(100) CONSTRAINT NN_OBSERVACAO_VENDAS NOT NULL,
	DATA_VENDA TIMESTAMP CONSTRAINT NN_VENDA_VENDAS NOT NULL,
	VALOR_TOTAL MONEY CONSTRAINT NN_VALOR_VENDAS NOT NULL,
	PESSOA INTEGER CONSTRAINT FK_PESSOA_VENDAS REFERENCES PESSOAS(COD_PESSOA)
);

CREATE TABLE TIPO_ESTOQUE
(
	COD_TIPO_ESTOQUE SERIAL CONSTRAINT PK_TIPO_ESTOQUE PRIMARY KEY,
	DESCRICAO VARCHAR(30) CONSTRAINT NN_DESCRICAO_TIPO_ESTOQUE NOT NULL
);

CREATE TABLE TIPO_MOVIMENTACAO
(
	COD_TIPO_MOVIMENTACAO SERIAL CONSTRAINT PK_TIPO_MOVIMENTACAO PRIMARY KEY,
	DESCRICAO VARCHAR(30) CONSTRAINT NN_DESCRICAO_TIPO_MOVIMENTACAO NOT NULL
);

CREATE TABLE PRODUTOS
(
	COD_PRODUTO SERIAL CONSTRAINT PK_PRODUTOS PRIMARY KEY,
	PRODUTO VARCHAR(30) CONSTRAINT NN_PRODUTO_PRODUTOS NOT NULL,
	PRECO MONEY CONSTRAINT NN_PRECO_PRODUTOS NOT NULL
);

CREATE TABLE LOTES
(
	COD_LOTE SERIAL CONSTRAINT PK_LOTES PRIMARY KEY,
	DATA_ENTRADA TIMESTAMP CONSTRAINT NN_DATA_ENTRADA_LOTES NOT NULL,
	VECIMENTO TIMESTAMP CONSTRAINT NN_VECIMENTO_LOTES NOT NULL,
	QTD_ITENS NUMERIC(10,2) CONSTRAINT NN_QTD_ITENS_LOTES NOT NULL,
	PRODUTO INTEGER CONSTRAINT FK_PRODUTO_LOTES REFERENCES PRODUTOS(COD_PRODUTO),
	FORNECEDOR INTEGER CONSTRAINT FK_FORNECEDOR_LOTES REFERENCES PESSOAS(COD_PESSOA)
);

CREATE TABLE PRODUTO_VENDIDO
(
	COD_VENDAS INTEGER,
	PRODUTO INTEGER,
	CONSTRAINT PK_PRODUTO_VENDIDO PRIMARY KEY (COD_VENDAS,PRODUTO),
	CONSTRAINT FK_COD_VENDAS_PRODUTO_VENDIDO FOREIGN KEY (COD_VENDAS) REFERENCES VENDAS(COD_VENDAS),
	CONSTRAINT FK_PRODUTO_PRODUTO_VENDIDO FOREIGN KEY (PRODUTO) REFERENCES PRODUTOS(COD_PRODUTO),
	QTD_VENDIDA NUMERIC(10,2) CONSTRAINT NN_QTD_VENDIDA_PRODUTO_VENDIDO NOT NULL,
	VALOR_UNITARIO MONEY CONSTRAINT NN_VALOR_UNITARIO_PRODUTO_VENDIDO NOT NULL
);

CREATE TABLE ESTOQUE
(
	COD_ESTOQUE SERIAL CONSTRAINT PK_ESTOQUE PRIMARY KEY,
	QTD_ANTERIOR NUMERIC(10,2) CONSTRAINT NN_QTD_ANTERIOR_ESTOQUE NOT NULL,
	QTD_ATUAL NUMERIC(10,2) CONSTRAINT NN_QTD_ATUAL_ESTOQUE NOT NULL,
	QTD_OPERACAO NUMERIC(10,2) CONSTRAINT NN_QTD_OPERACAO_ESTOQUE NOT NULL,
	DATA_ESTOQUE TIMESTAMP CONSTRAINT NN_DATA_ESTOQUE_ESTOQUE NOT NULL,
	PRODUTO INTEGER CONSTRAINT FK_PRODUTO_ESTOQUE REFERENCES PRODUTOS(COD_PRODUTO),
	TIPO_ESTOQUE INTEGER CONSTRAINT FK_TIPO_ESTOQUE_ESTOQUE REFERENCES TIPO_ESTOQUE(COD_TIPO_ESTOQUE),
	TIPO_MOVIMENTACAO INTEGER CONSTRAINT FK_TIPO_MOVIMENTACAO_ESTOQUE REFERENCES TIPO_MOVIMENTACAO(COD_TIPO_MOVIMENTACAO),
	LOTE INTEGER CONSTRAINT FK_LOTE_ESTOQUE REFERENCES LOTES(COD_LOTE),
	VENDA INTEGER CONSTRAINT FK_VENDA_ESTOQUE REFERENCES VENDAS(COD_VENDAS)
);